<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="3" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-10-03T13:55:20 IST" name="Suite" finished-at="2025-10-03T13:55:56 IST" duration-ms="35601">
    <groups>
      <group name="Purchase Product">
        <method signature="SubmitOrderTest.submitOrderTest(java.util.HashMap)[pri:0, instance:kynevtic.Test.SubmitOrderTest@1139b2f3]" name="submitOrderTest" class="kynevtic.Test.SubmitOrderTest"/>
      </group> <!-- Purchase Product -->
      <group name="Error Handling">
        <method signature="FailedLogin.loginFailTest()[pri:0, instance:kynevtic.Test.FailedLogin@7a69b07]" name="loginFailTest" class="kynevtic.Test.FailedLogin"/>
      </group> <!-- Error Handling -->
    </groups>
    <test started-at="2025-10-03T13:55:20 IST" name="Test" finished-at="2025-10-03T13:55:56 IST" duration-ms="35601">
      <class name="kynevtic.Test.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:kynevtic.Test.SubmitOrderTest@1139b2f3]" started-at="2025-10-03T13:55:34 IST" name="launchApplication" finished-at="2025-10-03T13:55:35 IST" duration-ms="937" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrderTest(java.util.HashMap)[pri:0, instance:kynevtic.Test.SubmitOrderTest@1139b2f3]" started-at="2025-10-03T13:55:35 IST" name="submitOrderTest" data-provider="getData" finished-at="2025-10-03T13:55:43 IST" duration-ms="8431" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=@Ragnarok2022, email=kratos@godofwar.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Product Added To Cart] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Product Added To Cart] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at kynevtic.Test.SubmitOrderTest.submitOrderTest(SubmitOrderTest.java:36)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrderTest -->
        <test-method is-config="true" signature="close()[pri:0, instance:kynevtic.Test.SubmitOrderTest@1139b2f3]" started-at="2025-10-03T13:55:43 IST" name="close" finished-at="2025-10-03T13:55:43 IST" duration-ms="107" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:kynevtic.Test.SubmitOrderTest@1139b2f3]" started-at="2025-10-03T13:55:43 IST" name="launchApplication" finished-at="2025-10-03T13:55:45 IST" duration-ms="1824" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrderTest(java.util.HashMap)[pri:0, instance:kynevtic.Test.SubmitOrderTest@1139b2f3]" started-at="2025-10-03T13:55:45 IST" name="submitOrderTest" data-provider="getData" finished-at="2025-10-03T13:55:54 IST" duration-ms="8772" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=@RE4Remake2023, email=leon@residentevil.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertFalse(Assert.java:79)
at org.testng.Assert.assertFalse(Assert.java:89)
at kynevtic.pageobjects.ProductsPagePOM.getProductName(ProductsPagePOM.java:40)
at kynevtic.pageobjects.ProductsPagePOM.addProductToCart(ProductsPagePOM.java:46)
at kynevtic.Test.SubmitOrderTest.submitOrderTest(SubmitOrderTest.java:34)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrderTest -->
        <test-method is-config="true" signature="close()[pri:0, instance:kynevtic.Test.SubmitOrderTest@1139b2f3]" started-at="2025-10-03T13:55:54 IST" name="close" finished-at="2025-10-03T13:55:54 IST" duration-ms="102" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- kynevtic.Test.SubmitOrderTest -->
      <class name="kynevtic.Test.FailedLogin">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:kynevtic.Test.FailedLogin@7a69b07]" started-at="2025-10-03T13:55:54 IST" name="launchApplication" finished-at="2025-10-03T13:55:55 IST" duration-ms="939" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginFailTest()[pri:0, instance:kynevtic.Test.FailedLogin@7a69b07]" started-at="2025-10-03T13:55:55 IST" name="loginFailTest" finished-at="2025-10-03T13:55:56 IST" duration-ms="799" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginFailTest -->
        <test-method is-config="true" signature="close()[pri:0, instance:kynevtic.Test.FailedLogin@7a69b07]" started-at="2025-10-03T13:55:56 IST" name="close" finished-at="2025-10-03T13:55:56 IST" duration-ms="83" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- kynevtic.Test.FailedLogin -->
      <class name="kynevtic.Test.VerifyProductPresence">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:kynevtic.Test.VerifyProductPresence@4a22f9e2]" started-at="2025-10-03T13:55:20 IST" name="launchApplication" finished-at="2025-10-03T13:55:22 IST" duration-ms="1629" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="verifyProductInCart()[pri:0, instance:kynevtic.Test.VerifyProductPresence@4a22f9e2]" started-at="2025-10-03T13:55:22 IST" name="verifyProductInCart" finished-at="2025-10-03T13:55:27 IST" duration-ms="4606" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyProductInCart -->
        <test-method is-config="true" signature="close()[pri:0, instance:kynevtic.Test.VerifyProductPresence@4a22f9e2]" started-at="2025-10-03T13:55:27 IST" name="close" finished-at="2025-10-03T13:55:27 IST" duration-ms="112" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:kynevtic.Test.VerifyProductPresence@4a22f9e2]" started-at="2025-10-03T13:55:27 IST" name="launchApplication" finished-at="2025-10-03T13:55:28 IST" duration-ms="929" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="verifyProductPresenceTest()[pri:0, instance:kynevtic.Test.VerifyProductPresence@4a22f9e2]" started-at="2025-10-03T13:55:28 IST" name="verifyProductPresenceTest" finished-at="2025-10-03T13:55:30 IST" duration-ms="1905" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyProductPresenceTest -->
        <test-method is-config="true" signature="close()[pri:0, instance:kynevtic.Test.VerifyProductPresence@4a22f9e2]" started-at="2025-10-03T13:55:30 IST" name="close" finished-at="2025-10-03T13:55:30 IST" duration-ms="99" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:kynevtic.Test.VerifyProductPresence@4a22f9e2]" started-at="2025-10-03T13:55:30 IST" name="launchApplication" finished-at="2025-10-03T13:55:31 IST" duration-ms="988" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="verifyActualProductInCart()[pri:0, instance:kynevtic.Test.VerifyProductPresence@4a22f9e2]" started-at="2025-10-03T13:55:31 IST" name="verifyActualProductInCart" finished-at="2025-10-03T13:55:34 IST" depends-on-methods="kynevtic.Test.VerifyProductPresence.verifyProductInCart" duration-ms="2987" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Product Added To Cart] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Product Added To Cart] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at kynevtic.Test.VerifyProductPresence.verifyProductInCart(VerifyProductPresence.java:42)
at kynevtic.Test.VerifyProductPresence.verifyActualProductInCart(VerifyProductPresence.java:48)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyActualProductInCart -->
        <test-method is-config="true" signature="close()[pri:0, instance:kynevtic.Test.VerifyProductPresence@4a22f9e2]" started-at="2025-10-03T13:55:34 IST" name="close" finished-at="2025-10-03T13:55:34 IST" duration-ms="126" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- kynevtic.Test.VerifyProductPresence -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
